### PR TITLE
feat: support BigQuery

### LINKED ISSUE #68: Add BigQuery to supported DBs?
Has anyone thought about extending this language server to support BigQuery as well?

I've looking into how I might develop a language server for BQ, and I stumbled upon this repo. Would it be simpler to develop my own from scratch or simply extend this one?

### PR DESCRIPTION
**Pull request by Leko**
I added a new database lib for BigQuery.
The SQL editor in the GCP console is not bad. But I'd like to use VSCode to write SQL for key-binding reason.

fix https://github.com/joe-re/sql-language-server/issues/68

### CODE REVIEW

**Comment by joe-re** [comment]
@Leko Hi, seems the error on your forked is something related to rollup.
https://github.com/rollup/rollup/issues/3805
I've migrated our building tool to esbuild(https://github.com/joe-re/sql-language-server/pull/90) and it should be no prob for now.
Can you try to merge the latest release branch into your branch and test it again? Thanks.

**Comment by Matts966** [comment]
It would be very attractive if this PR is merged! @Leko :pray:

**Comment by Leko** [comment]
@joe-re SFLR, I've merged the latest release branch, and mark this PR ready for review.

**Comment by joe-re** [comment]
@Leko Thank! It looks great. 👍

**Pull request merged**
